### PR TITLE
Fix broken link to tricks.md in docs

### PR DESCRIPTION
**Pull request by karottenreibe**

### CODE REVIEW

**Comment by Canop** [comment]
I don't get it. The link seems to be OK to me. Did you change the wrong link or is there something escaping me ?

**Comment by karottenreibe** [comment]
It's broken for me when I go here and click on that link: https://github.com/Canop/broot/blob/master/website/docs/common-problems.md

I get 404 from GitHub.

**Comment by Canop** [comment]
Oh... I understand.
This website directory isn't meant as a directly usable documentation and it didn't occur to me that it could be: it's the source for this site: https://dystroy.org/broot/

**Comment by Canop** [comment]
I'll add a README.md at the top of the website directory to explain its purpose.
If you have a better idea, I'm interested.

**Comment by karottenreibe** [comment]
I see, makes sense :-) sorry for the spam!

Canop <notifications@github.com> schrieb am Mi., 2. Sept. 2020, 18:52:

**Comment by Canop** [comment]
> sorry for the spam! Canop <notifications@github.com> 

Now worry. This was confusing but you found something which was unclear so it was for the best ;)

**Pull request closed without merging**
