### PR TITLE
fix: expand the path passed to *Broot*

### PR DESCRIPTION
**Pull request by stevenxxiu**
Just renamed the branch. Same as [feat: expand paths passed to *Broot* in *Nushell* by stevenxxiu · Pull Request #677 · Canop/broot](https://github.com/Canop/broot/pull/677).

Forward all args besides `--outcmd`.

### CODE REVIEW

**Comment by Canop** [comment]
I need more info there, as I don't get what it's supposed to fix as path resolution works fine for me.

**Comment by stevenxxiu** [comment]
Does `br` work for you in *Nushell v0.76.0* though?

**Comment by Canop** [comment]
> Does `br` work for you in _Nushell v0.76.0_ (the latest) though?

You're right, it  doesn't with nu .76. Sorry that I didn't understand your meaning before

**Comment by Canop** [comment]
@stevenxxiu Can you check my last commit on main (fixing comments) ?

**Pull request merged**
