### PR TITLE
Add `toggle_tree` flag to show only items in the current dir

### PR DESCRIPTION
**Pull request by eldad**
This PR aims to address issue https://github.com/Canop/broot/issues/670

Thanks for creating and maintaining this tool!

### CODE REVIEW

**Comment by eldad** [comment]
This commit unintentionally changed the default behavior to not display the tree, I am pushing a commit to change the default behavior as it is currently.

**Comment by eldad** [comment]
The last commit is now the desired behavior, default to show the tree.

**Comment by Canop** [comment]
Having "toggle" in a launch argument isn't semantically right: most other arguments are toggles anyway. It also doesn't say whether it toggles towards enabling a tree view or disabling it.

IMO the right semantic is what we have for other toggles: a couple of launch arguments `--tree` and `--no-tree`. This would also make it possible to have `--no-tree` in `default_flags` in the config and to override it with `--tree` at launch.

(another option would be to just don't have a launch parameter as we can do `--cmd :toggle_tree`)

If you prefer, I can do the change myself starting from your last commit.

**Comment by eldad** [comment]
> Having "toggle" in a launch argument isn't semantically right: most other arguments are toggles anyway. It also doesn't say whether it toggles towards enabling a tree view or disabling it.

Yes, I agree. That is not intuitive.

> If you prefer, I can do the change myself starting from your last commit.

I added now the change as you suggested - please feel free to edit it further as you see fit.

**Pull request merged**
