### PR TITLE
fixed couple of broken links in the README.md : )

### PR DESCRIPTION
**Pull request by eddiehazel**

### CODE REVIEW

**Comment by Canop** [comment]
Thanks.

It's quite a pain right now to maintain both website/index.html and the README. I should probably generate one from the other one...

**Comment by eddiehazel** [comment]
doesn't seem insurmountable ( : 

a github action?

**Comment by Canop** [comment]
Or just change my existing build script (see the `.sh`), which has the bonus of running locally and thus avoiding pushing broken commits just to see the result.

**Comment by eddiehazel** [comment]
as yes that is way more neat 👌

**Pull request merged**
