### PR TITLE
website: amend `install-br.md` with a note for nushell

### PR DESCRIPTION
**Pull request by Schweber**
https://github.com/Canop/broot/issues/827

### CODE REVIEW

**Comment by Canop** [comment]
@FrancescElies @LudoPinelli @texastoland Your opinion on this would be welcome.

**Comment by texastoland** [comment]
I'm traveling this week and haven't read the other thread completely. I agree the difference between `alias` and `def` here is surprising and worth documenting. Worth mentioning in the Nushell Discord server too in case it can be made more predictable. Tag me if you do 👍🏼

**Comment by texastoland** [comment]
I mean you you identified an issue with Nushell not broot. Even though it works by design it was confusing regardless. If lazygit added a `lg` wrapper command should they document this behavior too?

The [XY problem](https://xy-problem.com/) is it wasn't intuitive that `br` works by changing the environment thus necessitating wrapping with `def --env`. Possible solutions include adding a warning to the compiler, making it more obvious in the LSP (with an inlay hint for example), or just clarifying the Nushell docs.

**Comment by FrancescElies** [comment]
I also got bit by this in the passt. While I agree it is confusing when comming from other shells, nushell actually dedicates an entire section to this topic inside [getting started](https://www.nushell.sh/book/thinking_in_nu.html#nushell-s-environment-is-scoped). What else could have done the nushell mantainers to avoid us being bit by this? 

I am fine with the description, maybe you can add the link above to the broot docs? The obvious disadvantage is that if nushell restructure their docs or moves them elsewhere the link needs to be updated. Either way if you decide to add it or not I am fine with it.

**Comment by Canop** [comment]
You guys know nushell better than me. I wait for an explicit approval before merging.

**Comment by FrancescElies** [comment]
From my side all good, you can merge

**Pull request merged**
