### PR TITLE
support of multi-keys combinations, termimad 0.28

### PR DESCRIPTION
**Pull request by Canop**
With this PR comes the ability on terminals implementing [Kitty keyboard extensions](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) to bind verbs to key combinations which are normally not available on simple ANSI terminals, for example `space-n`, `ctrl-enter`, `shift-space`, `ctrl-alt-a-b-c`,  etc.

As a lot of things changed in the engine (i.e. in the crokey and termimad libraries), this PR comes also with risks of regressions.

### CODE REVIEW

**Comment by jinliu** [comment]
When enabled, this introduces conceivable delay with function keys (up, down, pgup, pgdn), on Kitty master (https://github.com/kovidgoyal/kitty#commit=4a64f812ad046b4aea023b85a0ce258da2c5572e).

**Comment by Canop** [comment]
Do you see a bigger delay than for other keys ?

I wonder if I shouldn't change the approach: instead of waiting for the key release, I could could react on key press unless there's a modifier (ctrl, alt, shift, maybe space) key pressed. This would prevent multi-key combinations without modifier key but would be faster for standard keys (including function keys).

**Comment by jinliu** [comment]
I feel all keys have delays. Even when entering verbs, where I think very little processing is happening. My estimate is ~100-200ms.

With the option disabled, I don't feel any delay at all.

**Comment by Canop** [comment]
100-200ms ? Damn... That's absolutely not the key release problem then. I'll have to try with the last kitty to see if I reproduce.

**Comment by Canop** [comment]
It should be better now (still no explanation for such a delay, but most combinations are now built on key press).

**Comment by jinliu** [comment]
It works. Now the latency is barely noticable.

I can still feel a tiny bit of it. But it may well be mental. I'd add some timer code between keypress and screen actually updating to verify.

**Comment by Canop** [comment]
Current blocking problem: I can't manage to get the caret key on wezterm (it works fine on kitty).

**Comment by Canop** [comment]
There are other problems in wezterm, eg the ':' key.
See https://github.com/wez/wezterm/issues/4785
So I prefer to make the support of this protocol opt-in rather than opt-out.

**Pull request merged**
