### PR TITLE
Extend 'apply_to' with 'text_file' and 'binary_file'

### LINKED ISSUE #764: Automatically open text files with `$EDITOR`
Terminal file managers like `nnn`, `lf`, `yazi` can automatically detect text files and open them in your `$EDITOR`, instead of `xdg-open`. `broot` requires you to specify an explicit key for this, I think it'd be more convenient if we can use a single key to open anything.

### PR DESCRIPTION
**Pull request by Canop**
This makes it possible, for example, to have text files open in the same terminal on 'enter':

```Hjson
{
    invocation: edit
    key: enter
    shortcut: e
    execution: "/usr/bin/nvim +{line} {file}"
    apply_to: text_file
    leave_broot: false
}
```

Fix #764

### CODE REVIEW

**Comment by musjj** [comment]
I'm trying to build this, but for some reason I keep getting this error:

```rust
       > error[E0425]: cannot find function `is_file_known_binary` in module `magic_numbers`
       >   --> src/content_type/mod.rs:27:20
       >    |
       > 27 |     magic_numbers::is_file_known_binary(path)
       >    |                    ^^^^^^^^^^^^^^^^^^^^ not found in `magic_numbers`
       >
```

Is it a typo of this function?:

https://github.com/Canop/broot/blob/aead8106a202d900439be867c11a0c29a55565aa/src/content_search/magic_numbers.rs#L76

**Comment by Canop** [comment]
But the function is in the PR files: https://github.com/Canop/broot/pull/769/files#diff-875aa6ab1b4041dd7920d66de1999be6a1af4e3c5c00d467211ec70015ec543bR120

**Comment by Canop** [comment]
@musjj if it looks easier for solving this problem, please come to the chat https://miaou.dystroy.org/3490

**Comment by musjj** [comment]
Weird, I was applying this PR as a patch on top of the main branch, so I decided to just build the feature branch directly and now it works. I guess something went wrong with my nix derivation.

I tested the new `apply_to: text_file` and it seems to work perfectly!

**Comment by Canop** [comment]
I'll keep the branch unmerged for tests for a week, I think.

Among the downsides, it's harder to open SVG files as images.

**Comment by musjj** [comment]
I'll use this as a daily driver and report any issues I may encounter. 

So far I don't really mind svg being opened as text files, since I can just type ` os` if I really want to open an image viewer/editor. Most of the time I'm interacting with svg files in the terminal is when I'm trying to edit them as a text file, but I guess that varies between users.

But maybe if you want it to be more flexible, how about something like a new `disallowed_extensions` option (the opposite of `extensions`)?

**Comment by Canop** [comment]
> But maybe if you want it to be more flexible, how about something like a new disallowed_extensions option (the opposite of extensions)?

I must be cautious or I'll end up with a scripting language just to decide what verbs apply...

**Comment by jinliu** [comment]
Works for me. And perhaps this should be in the default config file.

**Comment by Canop** [comment]
> And perhaps this should be in the default config file.

I'm still unsure about that: it means the enter key won't work for people without a $EDITOR. And it won't suit people whose editor isn't a terminal one.

**Comment by FrancescElies** [comment]
A bit late to help but this works fine for me under windows+nushell, default binding `ctrl-e` opens nvim just fine.

**Comment by Canop** [comment]
> A bit late to help 

A late report is much better and more appreciated than no report. Thanks.

**Pull request merged**
