### PR TITLE
feat: expand paths passed to *Broot* in *Nushell*

### PR DESCRIPTION
**Pull request by stevenxxiu**
Expand home directory in paths.

### CODE REVIEW

**Comment by Canop** [comment]
Can you tell more about what's solved by this PR ?

**Comment by stevenxxiu** [comment]
So currently if you put this in *Nushell*:

    $ br ~/foo/

It will error out saying there's no such directory. This PR expands the paths so it works.

**Comment by stevenxxiu** [comment]
Hmm which version of *Nushell* are you using?

**Comment by Canop** [comment]
image

**Comment by Canop** [comment]
@stevenxxiu  What happened exactly ? Was it a nushell version problem ?

**Pull request closed without merging**
