### PR TITLE
add vim-floaterm broot wrapper link

### PR DESCRIPTION
**Pull request by voldikss**
That plugin supports both nvim and vim.

### CODE REVIEW

**Comment by Canop** [comment]
Interesting.

I'll have to have a deeper look at floaterm before I link to it: there seems to be a problem in [the plugin](https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/wrapper/broot.vim), maybe a problem of compatibility with last broot, it doesn't work correctly on my computer (b&w broot, no selection shown).

**Comment by voldikss** [comment]
Thank you for the attention!

**Comment by voldikss** [comment]
> maybe a problem of compatibility with last broot

Is that the incompatibily of config file (hjson v.s. toml)?

**Comment by Canop** [comment]
No, hjson or toml aren't a problem, maybe the way removing colors is decided. It's possible a `--color auto` would be needed. But I should fork your project to try test to be sure.

**Pull request closed without merging**
