### PR TITLE
Internals for changing the widths of panels

### PR DESCRIPTION
**Pull request by Canop**
3 new internals:

* `set_panel_width`, taking as parameter the index of the panel and the desired width
* `move_panel_divider`, taking as parameter the index of the divider and the desired change
* `default_layout`, restores the default panel sizes

`ctrl-<` is bound by default to `:move_panel_divider 0 -1`

`ctrl->` is bound by default to `:move_panel_divider 0 1`

It's also possible to define the layout in conf, eg 

```
    layout_instructions: [
         { panel: 0, width: 18 }
     ]
```

### CODE REVIEW

**Comment by FrancescElies** [comment]
Shortly tested on windows with wezterm using US keyboard input.

image

I was not able to resize panes, on the right side you the key strokes I tried `< (shift+,)` `> (shift+.)`  `ctrl+< ((ctrl+shift+,))`and  `ctrl+> (ctrl+shift+,)`

This issue I am seeing might be related to #818

**Comment by FrancescElies** [comment]
It's funny, pressing `<` and `>` in combination with `ctrl-shift` and `alt-shift`.

Print key shows the following.
image

At any rate, since this option is configurable and the issue seems to be with windows and one of the broo deps, the following bindings is a good workaround under windows.
```
    {
        invocation: move_divider_left
        key: ctrl-shift-,
        execution: ":move_panel_divider 0 -1"
        leave_broot: false
    }
    {
        invocation: move_divider_right
        key: ctrl-shift-.
        execution: ":move_panel_divider 0 1"
        leave_broot: false
    }
```

Unless you need any further testing from my side I will leave it here.

**Comment by Canop** [comment]
Those comma and dot bindings aren't easy to type either. I still take suggestions.

**Comment by FrancescElies** [comment]
They are for me on the same place as `<` `>`.

image

Honestly I don't have any good proposal.

**Pull request merged**
