### PR TITLE
Rewrote the parse_command_sequence function.

### PR DESCRIPTION
**Pull request by Lucretiel**
Implements https://github.com/Canop/broot/issues/142

### CODE REVIEW

**Comment by Canop** [comment]
For next PR, please don't reformat lines you didn't touch. standard fmt often break the consistency and readability of the code.

**Comment by Lucretiel** [comment]
Does this project not conform to rustfmt?

**Comment by Canop** [comment]
This is a separate question. This PR touches a lot of things. Right now reviewing this PR is probably more work for me than rewriting the command sequence parsing.

**Comment by Lucretiel** [comment]
I can split up the PR into different parts, if you'd like, but that'll have to wait till tomorrow because I need to sleep.

**Comment by Lucretiel** [comment]
Or you can duplicate 18 hours of work if you think it'll take more than that to review this?

**Comment by Canop** [comment]
Go to sleep, we have a life. I won't deploy this today.

The one thing I'd like to deploy in next version is the command parsing. We'll discuss other points before thinking about PR.

But the discussion can wait until tomorrow.

**Comment by Lucretiel** [comment]
> The one thing I'd like to deploy in next version is the command parsing. We'll discuss other points before thinking about making relevant PR.

If you're thinking you want to introduce general command parsing into the interactive UI, it might make more sense to close this PR and do the implementation there, more tightly integrated with the Command / VerbInvocation structs. Then the `--cmd` parameter can just defer to that instead of duplicating a lot of the parsing work, like we do right now.

**Comment by Canop** [comment]
Closing. We'd better discuss this on the chat.

**Pull request closed without merging**
