### PR TITLE
Preview transformers

### LINKED ISSUE #494: Use mutool draw for previewing PDFs
MuPDF's `mutool draw` command produces a decently high-resolution image form of a PDF. It can be specified to only produce an image of the first page, which would be nice for previewing PDFs.

Quick demo (after installing MuPDF):

```bash
$ mutool draw -o pdf-preview.png julia-1.5.0.pdf 1 # can add 2>/dev/null
page julia-1.5.0.pdf 1
$ kitty +kitten icat pdf-preview.png
```

Or directly through stdout:

```bash
mutool draw -o - julia-1.5.0.pdf 1 2>/dev/null | kitty +kitten icat
```

### PR DESCRIPTION
**Pull request by Canop**
This allows defining file transformations that are applied to files before preview.

The default conf has 2 examples: previewing PDF and beautifying JSON: 

```Hjson
preview_transformers: [
     # Use mutool to render any PDF file as an image
     # In this example we use placeholders for the input and output files
     {
         input_extensions: [ "pdf" ] // case doesn't matter
         output_extension: png
         mode: image
         command: [ "mutool", "draw", "-o", "{output-path}", "{input-path}" ]
     }

     # Use jq to beautify JSON
     # In this example, the command refers to neither the input nor the output,
     # so broot pipes them to the stdin and stdout of the jq process
     {
         input_extensions: [ "json" ] 
         output_extension: json
         mode: text
         command: [ "jq" ]
     }
]
```

PDF preview:

image

JSON beautification (the original file has no space nor new line):

image

Fix #494

### CODE REVIEW

**Comment by Canop** [comment]
BTW, I'd welcome suggestion of transformers for the website (and my own usage)

**Comment by eddiehazel** [comment]
both verified iterm/macos in principle, pdf image a little blurry but perhaps that is outside broot's hands?

Screenshot 2024-07-07 at 13 44 53

excited to see what else can be done with this feature! ( :

**Comment by Canop** [comment]
@eddiehazel The image is blurry here because your terminal doesn't support the [Kitty protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) which broot uses to display high-res images.

**Comment by eddiehazel** [comment]
thanks, looking into it!

```
   # Use fold to wrap text
    # In this example, the command refers to neither the input nor the output,
    # so broot pipes them to the stdin and stdout of the jq process
    {
        input_extensions: [ "txt" ]
        output_extension: txt
        mode: text
        command: [ "fold", "-w 80", "-s" ]
    }
]
```

working well 💫

**Comment by Canop** [comment]
IMO wrapping should be done by broot so that the line numbers stay consistent (usually you want to jump to the right place when opening the file), but that's an interesting first step before I implement wrapping in broot.

**Comment by eddiehazel** [comment]
for sure, just playing around and it works for now ( : 

so i need to switch terminal to get kitty support because everyone has their own protocol 😭 

i thought to make a transformer for this with `timg` but i guess it's lower level

i will take a look at some alternatives

**Comment by Canop** [comment]
> so i need to switch terminal to get kitty support because everyone has their own protocol 😭
> 
> i thought to make a transformer for this with timg but i guess it's lower level

This can't really be a transformer. The protocol of iterm2 could probably be implemented in broot the same way I implemented the kitty protocol but I can't do it myself as I don't own a Mac.

**Comment by eddiehazel** [comment]
seems there is a lot of inspiration here: https://github.com/lusingander/iterm2img

not sure if it's quite within my wheelhouse but i'll try size it up - wdyt? 

definitely up for testing either way! 🤲

**Comment by Canop** [comment]
> not sure if it's quite within my wheelhouse but i'll try size it up

Even if you don't manage to finish, clarifying the problems and possible solutions would both be enlightening and useful, so you probably should. And you can come to miaou to discuss your findings.

But we're going off the topic of this PR, so I suggest you create an issue for item2 support in broot (or for high-res image support on mac if you prefer it less specific).

**Comment by FrancescElies** [comment]
I personally don't particularly care about this feature but gave it a try on a mac anyways, @Canop I hope this helps.

|name|version|
|-|-|
|nu|0.95.0|
|wezterm|20240203-110809-5046fc22|
|os|macos|

Not sure if this is an issue of broot or any other part of my setup but pdfs and images for whatever reason don't fully utilize the space available for the preview panel.
[pdf](https://google.github.io/comprehensive-rust/comprehensive-rust.pdf)
grafik
[image](https://i.pinimg.com/originals/0e/8a/71/0e8a7189ee4789c4873d236c3702c8a8.png)
grafik

**Comment by Canop** [comment]
> pdfs and images for whatever reason don't fully utilize the space available for the preview panel.

All images ? Or just the ones coming from pdf transformation ?

**Comment by FrancescElies** [comment]
Nevermind, I think the images I downloaded where just simply too small.

grafik


The issue seems to be related to the pdf image transformation, maybe one needs to do something with mutool

**Comment by Canop** [comment]
You can increase the image width:

    {
        input_extensions: [ "pdf" ] // case doesn't matter
        output_extension: png
        mode: image
        command: [ "mutool", "draw", "-w", "1000", "-o", "{output-path}", "{input-path}" ]
    }

**Comment by Canop** [comment]
I could probably define some `{preview-width}` parameter...

**Pull request merged**
