### PR TITLE
Trash state

### LINKED ISSUE #855: Add features for Trash management
As broot now includes the `trashy` crate for the `:trash` internal (if i understand it correctly), it could make use of more of its features for managing the Trash.

I would like to have commands to
- `cd` into the system trash directory
- restore files
- clear the Trash directory

This way, broot could replace [trashy](https://github.com/oberblastmeister/trashy), which is not up-to-date anyway.

### PR DESCRIPTION
**Pull request by Canop**
`:open_trash` shows the content of the trash.

Other new internals & verbs: `:delete_trashed_file`, `:restore_trashed_file`, `:purge_trash`.

All this is available only when broot is compiled with the `trash` feature.

Fix #855

### CODE REVIEW

**Comment by FrancescElies** [comment]
works fine on linux + gnome + nushell.

When calling `:open_trash` is it possible to see the dates the files where deleted and sort them to see what was recently deleted?

**Comment by Canop** [comment]
> When calling :open_trash is it possible to see the dates the files where deleted and sort them to see what was recently deleted?

Not yet. It's on the todo list but it's probable I'll do that later because of a deep broot change I'm working on.

**Comment by FrancescElies** [comment]
works fine on windows 11 + nushell (test: `cargo r -F trash`, trash a file, restore and empty trash)

**Comment by Canop** [comment]
You just taught me that it was possible to shorten `cargo run --features` in `cargo r -F`... I had no idea...

**Pull request merged**
