### PR TITLE
optionally show lines surrounding a match in preview

### LINKED ISSUE #756: Context lines for content matches
When searching file content with `c/...`, I can open the preview pane and then cycle through matches, but I only get the exact line that matched. I'd really like to have the matching line centered in a regular preview and to be able to cycle through the matches that way. Alternatively, having *n* lines of context before and after the match (like `rg`) would be nice.

### PR DESCRIPTION
**Pull request by Canop**
New settings:

```
###############################################################
# lines around matching line in filtered preview
#
# When searching the content of a file, you can have either
# only the matching lines displayed, or some of the surrounding
# ones too.
#
lines_before_match_in_preview: 1
lines_after_match_in_preview: 1
```

Fix #756

### CODE REVIEW

**Comment by stevenxxiu** [comment]
Thanks for this. Could there be a horizontal line break of sorts, between search results that aren't next to each other?

**Comment by Canop** [comment]
Can you check if everything looks right ?

note: there's no separator when lines_before and lines_after are 0, to keep it dense.

**Comment by stevenxxiu** [comment]
Thanks! Looks good to me.

**Comment by Canop** [comment]
I need to support the tab to go to next match

**Comment by Canop** [comment]
Done. Now you can go to next match with `tab` and the previous one with `shift-tab` (with default bindings).

This is needed since the down and arrow keys don't jump to the next/previous matching line.

**Comment by Canop** [comment]
Question is... Should I set `lines_before_match_in_preview` and `lines_after_match_in_preview` to `0` or `1` by default ?

**Comment by stevenxxiu** [comment]
Up to you I suppose.

*Ripgrep* itself doesn't enable this by default.

Setting this to 0 will keep the previous behavior, and 1 will help people notice this feature.

Personally I set this to 2.

**Pull request merged**
